### ISSUE TITLE
Postgresql service issue with worker deployment

### ISSUE THREAD

**Issue by CheckYourGages** [deislabs/helm-workshop#20]
The postgresql database is inaccessible to the worker using the current configuration. To work around this for the tutorial, there is a workaround by creating a second service for the worker and database to communicate across.
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    chart: postgresql-3.1.0
    release: {{ .Release.Name }}
  name: db
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
```
paste this below the worker deployment in your yaml file, and it should allow them to communicate.
